### ISSUE TITLE
nim-status-go shim

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#5]
Nim-status-go shim
===

## Introduction

As a first step a shim layer would allow status-react to start using the nim library as soon as possible, we can then add new apis or replace status-go apis with nim ones in a steady, iterative manner instead of a big branch approach. Since the API is the same, that library should work without almost any changes required from status-react.

## Approach

Using status-go as library in nim has been shown in nim-status-client as seen [here](https://github.com/status-im/nim-status-client/blob/master/src/status/libstatus/libstatus.nim)

```nimrod=
proc hashMessage*(p0: cstring): cstring {.importc: "HashMessage".}

proc initKeystore*(keydir: cstring): cstring {.importc: "InitKeystore".}

proc openAccounts*(datadir: cstring): cstring {.importc: "OpenAccounts".}

proc multiAccountGenerateAndDeriveAddresses*(paramsJSON: cstring): cstring {.importc: "MultiAccountGenerateAndDeriveAddresses".}

proc multiAccountStoreDerivedAccounts*(paramsJSON: cstring): cstring {.importc: "MultiAccountStoreDerivedAccounts".}

proc multiAccountImportMnemonic*(paramsJSON: cstring): cstring {.importc: "MultiAccountImportMnemonic".}

proc MultiAccountImportPrivateKey*(paramsJSON: cstring): cstring {.importc: "MultiAccountImportPrivateKey".}

proc multiAccountDeriveAddresses*(paramsJSON: cstring): cstring {.importc: "MultiAccountDeriveAddresses".}

proc saveAccountAndLogin*(accountData: cstring, password: cstring, settingsJSON: cstring, configJSON: cstring, subaccountData: cstring): cstring {.importc: "SaveAccountAndLogin".}

proc callRPC*(inputJSON: cstring): cstring {.importc: "CallRPC".}

proc callPrivateRPC*(inputJSON: cstring): cstring {.importc: "CallPrivateRPC".}

proc addPeer*(peer: cstring): cstring {.importc: "AddPeer".}

proc setSignalEventCallback*(callback: SignalCallback) {.importc: "SetSignalEventCallback".}

proc sendTransaction*(jsonArgs: cstring, password: cstring): cstring {.importc: "SendTransaction".}

proc generateAlias*(p0: GoString): cstring {.importc: "GenerateAlias".}

proc identicon*(p0: GoString): cstring {.importc: "Identicon".}

proc login*(acctData: cstring, password: cstring): cstring {.importc: "Login".}

proc logout*(): cstring {.importc: "Logout".}
```

To get the shim working, we can create a striped down version of the build system of nim-status-client that only uses libstatus (i.e not QT nor any other libraries) and outputs an static library that then can be used in status-react.

to summarize:
* 1. create simple nim project that interacts with status-go
* 2. compile project as a static library
* 3. integrate with status-react

## Tests

There should be tests in nim for each of the exposed APIs to ensure they are working as expected.

## Existing work

* https://github.com/status-im/nim-status-client/blob/master/src/status/libstatus/libstatus.nim
* https://github.com/richard-ramos/lib_nimstatus/blob/master/src/libstatus.nim

## Potential problems / issues to explore

* compiling it as a static library correctly
* unclear if strings will work out of the box or not, there are two types of strings `cstring` and `GoString`, when re-exposing these apis we should make sure it still works as expected
* receiving signals from status-go and passing them through the nim library to the client, unclear if a shim for `setSignalEventCallback` will work as expected

note: the spec part of this task will be added to status-im/specs later

**Comment by arnetheduck** [comment]
> Since the API is the same, that library should work without almost any changes required from status-react.

from a practical pov, it might make sense to to name the exported symbols slightly differently - in v0.1, we could prefix them with `ni` or whatever, and offer up versions that simply forward the call their corresponding `go` implementations - from there onwards, status-react will be completely ignorant of where things are implemented.

there is reason to put two shims in place - this is a very common strategy when doing language interop:

* `shim-n`: hides `status-go` vs `status-nim` from nim consumers - offers the shim with `nim` types and "feeling"
* `shim-c`: calls `shim-n` (is a "nim consumer") and translates that to a language-independent lowest-common-denominator approach in terms of what API is offered so that it's easy to import/export in any language - status-react or any other project.

as far as development goes, putting `shim-c` in place that calls a fully `status-go`-based `shim-n` is a risk-free way of injecting the shim functionality into the build of status-react.

**Comment by iurimatias** [comment]
@Samyoul pointed out there is a document detailing the api currently used https://github.com/status-im/specs/issues/136 this what we should use as a reference
